In [1]:
# !pip install gensim
# !pip install python-Levenshtein

In [2]:
import gensim
import pandas as pd

In [3]:
df=pd.read_excel(r'finalTrainingData.xlsx')
df.tail()

                                                desc         hts
513157  lavish home reversible alternative comforter  9404908522
513158          wawel czekolada dark 70% gorzka 100g  1806329000
513159                                 et 1l cracw 1  4821109000
513160              camilo c , table60 marble w / gr  9403600000
513161             32 h wooden block joy porch sign"  9505105020

In [4]:
# df.loc[df['REMOTE_LOCATION']=='48759-3434153-CastlegateHBL_MAEUNPO1369700_HDMUNBOZ36987900_HDMUNBOZ369879A1-1.png','text']

In [5]:
# df=df.loc[df['DOCUMENT_TYPE']!=0]
df['hts'].value_counts()

6911103750    6159
9403608081    3887
9403509045    2689
5702420000    1897
9401616011    1783
              ...
6702104000    1500
2001909791    1500
6910100030    1500
9402100000    1500
6306229030    1500
Name: hts, Length: 336, dtype: int64

In [6]:
len(df)

513162

In [7]:
# counter = 0

# for index, i in enumerate(df['text']):
#     i = i.replace('\n', ' ')
#     for word in str(i).split(" "):
#         if len(word) > 15:
#             counter+=1
#             print()
#             print(len(word))
#             print(word)
#             break
# counter
# # df['text'][0]

In [8]:
df = df[df.desc.str.contains(' ', na=False)]

review_text = df.desc.apply(gensim.utils.simple_preprocess)

In [9]:
review_text

0           [wexford, red, dinner, plates, rd, gb, wexgrnb]
1                                       [std, lr, ell, wpb]
2                      [cukierki, nimm, witaminami, storck]
3                                  [load, levelling, valve]
4                          [filtr, oleju, fiat, doblo, jtd]
                                ...
513157    [lavish, home, reversible, alternative, comfor...
513158                     [wawel, czekolada, dark, gorzka]
513159                                          [et, cracw]
513160                          [camilo, table, marble, gr]
513161                    [wooden, block, joy, porch, sign]
Name: desc, Length: 496744, dtype: object

In [10]:
# review_text[15183]

In [11]:
# from gensim.test.utils import common_texts, get_tmpfile
# from gensim.models import Word2Vec
# from gensim.models.callbacks import CallbackAny2Vec

# class callback(CallbackAny2Vec):
#     '''Callback to print loss after each epoch.'''

#     def __init__(self):
#         self.epoch = 0

#     def on_epoch_end(self, model):
#         loss = model.get_latest_training_loss()
#         print('Loss after epoch {}: {}'.format(self.epoch, loss))
#         self.epoch += 1

# # model = Word2Vec(common_texts, size=100, window=5, min_count=1, 
# #                  compute_loss=True, callbacks=[callback()])

In [12]:
# model = gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=6e-5,
#     vector_size=300,
#     compute_loss=True, callbacks=[callback()],
#     epochs=7
# )

In [13]:
# model= gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=6e-5
# )

In [14]:
# model= gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=1e-6
# )

In [15]:
# model= gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=1e-4
# )

In [16]:
# model= gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=1e-5
# )

In [17]:
# model= gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=9e-5
# )

In [18]:
# model= gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=9e-4
# )

In [19]:
# model= gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=9e-5
# )

In [20]:
# model= gensim.models.Word2Vec(
#     window=5,
#     min_count=1,
#     workers=4,
#     sample=9e-6
# )

In [21]:
model= gensim.models.Word2Vec(
    window=7,
    min_count=1,
    workers=4,
    sample=6e-5,vector_size=300
)

# model_2= gensim.models.Word2Vec(
#     window=7,
#     min_count=1,
#     workers=4,
#     sample=6e-5,vector_size=300
# )

In [22]:
model.build_vocab(review_text, progress_per=1000)
# model.build_vocab(review_text, progress_per=1000)

In [23]:
model.train(review_text, total_examples=model.corpus_count, epochs=model.epochs)

(7113273, 11440270)

In [24]:
# sentences=list(df.text)

In [25]:
# !pip install --upgrade gensim

In [26]:
# pip list

In [27]:
# from gensim.sklearn_api import W2VTransformer
# from sklearn.model_selection import GridSearchCV
# from sklearn.metrics import accuracy_score, make_scorer

# s_obj = W2VTransformer(size=100)

# parameters = {'window':(5,10,15),'min_count':(1,2,4)}

# # s_model = GridSearchCV(s_obj,parameters,cv=2)
# s_model = GridSearchCV(s_obj,parameters, scoring=make_scorer(accuracy_score))

# s_model.fit(review_text)

# print(s_model.best_params_)

In [28]:
# from gensim.test.utils import common_texts
# common_texts

In [29]:
# model.save("./word2vec-using-gensim.model")

In [30]:
from gensim.models import KeyedVectors

In [31]:
# Store just the words + their trained embeddings.
word_vectors = model.wv
word_vectors.save("word2vec_htsFinalTrainingData.wordvectors")

In [32]:
wv = KeyedVectors.load("word2vec_htsFinalTrainingData.wordvectors", mmap='r')

In [33]:
# wv_2 = KeyedVectors.load("word2vec_augmented_augmented_updated_nlp_done_lemmatized_6e-5_300_win_7.wordvectors", mmap='r')

In [34]:
# wv_2['zone']

In [35]:
# wv['zone']

In [36]:
# wv_2.most_similar('vessel')

In [39]:
model.wv.most_similar("chair")

[('rostock', 0.845950722694397),
 ('treatment', 0.8436311483383179),
 ('xy', 0.8319669365882874),
 ('blizzard', 0.8275760412216187),
 ('lashes', 0.8261263370513916),
 ('ivette', 0.8218719959259033),
 ('reagan', 0.818252682685852),
 ('shumacher', 0.8155107498168945),
 ('bellevue', 0.8112028241157532),
 ('dining', 0.8099753856658936)]

In [41]:
model.wv.most_similar("furniture")

[('couch', 0.8384209275245667),
 ('wheeled', 0.8337068557739258),
 ('office', 0.7836503982543945),
 ('coventry', 0.7763373851776123),
 ('colorado', 0.7671786546707153),
 ('closet', 0.7581614851951599),
 ('linden', 0.7581315636634827),
 ('olstered', 0.7578588128089905),
 ('moving', 0.755333662033081),
 ('bolste', 0.7550448179244995)]

In [39]:
model.wv.most_similar("zone")

[('town', 0.7556388974189758),
 ('district', 0.7454279065132141),
 ('develop', 0.7255854606628418),
 ('industri', 0.7248048186302185),
 ('provinc', 0.7162231802940369),
 ('sheng', 0.695965588092804),
 ('zhejiang', 0.682959258556366),
 ('huizhou', 0.6727529764175415),
 ('jiang', 0.6694082021713257),
 ('luoyang', 0.6670336127281189)]

In [ ]:
# wv_2.most_similar('zone')

In [44]:
wv_2.most_similar('weight')

[('gross', 0.8439235687255859),
 ('kg', 0.7610828280448914),
 ('total', 0.7282893657684326),
 ('quantity', 0.7198747992515564),
 ('measurement', 0.7183003425598145),
 ('cbm', 0.685063898563385),
 ('package', 0.6820922493934631),
 ('pallet', 0.6777692437171936),
 ('net', 0.6775811314582825),
 ('description', 0.6684989333152771)]

In [37]:
model.wv.most_similar("weight")

[('gross', 0.838156521320343),
 ('kg', 0.7437127232551575),
 ('measur', 0.7319930791854858),
 ('total', 0.7295935153961182),
 ('quantiti', 0.7114863395690918),
 ('packag', 0.6879239082336426),
 ('pallet', 0.6876823902130127),
 ('net', 0.6783446073532104),
 ('nett', 0.6572309136390686),
 ('cbm', 0.6396167874336243)]

In [37]:
model.wv.most_similar("weight")

[('gross', 0.8531695604324341),
 ('kg', 0.7877658605575562),
 ('measur', 0.787743330001831),
 ('total', 0.7318695783615112),
 ('quantiti', 0.7200117111206055),
 ('packag', 0.7128152251243591),
 ('cbm', 0.6974779367446899),
 ('pallet', 0.6914093494415283),
 ('kilo', 0.6871155500411987),
 ('net', 0.6692990660667419)]

In [36]:
# model.wv.most_similar("notice")

In [32]:
model.wv['zone']

array([-1.88528016e-01, -4.31258053e-01,  5.79042375e-01,  3.05005938e-01,
       -4.35556412e-01, -1.36682093e-01, -1.42982468e-01,  1.37720034e-01,
       -6.75675154e-01, -5.76798558e-01,  4.40493263e-02,  5.39672911e-01,
       -5.94543219e-01,  6.86391532e-01, -1.16921455e-01, -2.55154729e-01,
       -2.98690647e-01, -2.23723575e-01, -7.18584180e-01,  6.14137888e-01,
       -6.69286260e-03, -5.77483773e-01,  1.25561881e+00,  2.19308138e-01,
       -5.68856955e-01,  1.56532609e+00, -4.54786301e-01, -1.12937093e+00,
       -7.12194383e-01, -4.22803849e-01,  6.08687401e-01,  5.37833273e-01,
       -7.82175362e-01,  1.29907501e+00, -1.40590322e+00, -1.24604087e-02,
        8.79062355e-01, -5.89669272e-02, -5.64991415e-01,  3.30133021e-01,
       -1.13320313e-02, -1.00313556e+00,  5.67413330e-01,  7.92829633e-01,
       -1.37735689e+00, -3.66172403e-01,  3.96012306e-01,  1.97842017e-01,
       -8.90435278e-01,  1.61869979e+00, -5.96987426e-01, -9.74520385e-01,
        6.19746521e-02, -6.93224967e-02,  7.64727890e-01, -7.97129944e-02,
        1.19651699e+00, -4.11101431e-01, -9.71530825e-02,  9.85858440e-01,
        1.27740055e-01, -4.13663298e-01,  1.48717630e+00, -1.14993536e+00,
        2.24737167e+00,  2.65997559e-01, -1.33585930e-01, -4.32459354e-01,
        1.93752013e-02,  9.68857706e-01,  3.83114308e-01,  1.01165080e+00,
       -1.17372543e-01,  6.01783395e-01,  2.61284232e-01, -2.32896462e-01,
       -3.71751636e-01,  7.52191484e-01, -1.18040271e-01,  5.19874215e-01,
       -4.28705275e-01, -9.07095253e-01,  7.46591747e-01, -8.19483638e-01,
       -4.03231353e-01,  4.15637225e-01,  4.83123869e-01,  9.90983129e-01,
        4.61302310e-01,  1.17650056e+00,  7.28969336e-01,  1.46160090e+00,
       -5.12326479e-01,  6.87527731e-02, -1.59294665e+00,  1.81282446e-01,
       -1.13929555e-01, -6.33722365e-01, -9.39865410e-01, -9.86073613e-01,
        1.10702944e+00, -1.06555593e+00, -2.20046788e-01, -4.02772635e-01,
       -1.06452250e+00, -3.38040143e-01, -1.04481852e+00,  1.58435985e-01,
       -1.23740959e+00, -1.05831027e+00,  1.03176928e+00, -1.30428386e+00,
        1.42599118e+00,  8.93985808e-01,  6.21664822e-02, -5.11980832e-01,
       -8.93901765e-01,  3.36911261e-01,  6.12518668e-01,  3.24200511e-01,
        4.78914827e-01,  9.24123168e-01, -6.01414144e-01,  4.05835181e-01,
        4.81321197e-03, -3.33236843e-01,  1.65255225e+00, -1.21600771e+00,
        1.10178661e+00, -5.13248384e-01, -1.11008501e+00, -3.05163506e-02,
        2.59189785e-01, -1.39723265e+00,  1.92267215e+00, -8.84620845e-01,
       -5.67076921e-01,  5.57545841e-01, -5.17269783e-02,  4.55479145e-01,
       -1.55808032e-01, -6.21749103e-01,  7.02578366e-01, -9.25200462e-01,
        1.61333993e-01,  1.16080689e+00,  2.72491157e-01,  6.28429413e-01,
       -1.41388411e-03,  3.15921277e-01, -1.98988289e-01,  9.36623991e-01,
       -1.42428517e+00, -3.16209253e-03, -1.89247817e-01, -1.48512995e+00,
       -1.51279181e-01,  7.51916468e-01, -5.07922232e-01,  4.72840905e-01,
        2.84060776e-01,  7.54032373e-01,  1.41790047e-01, -3.09031755e-01,
        7.27686405e-01,  9.60147083e-01,  7.92609453e-01, -6.70175076e-01,
        1.38894832e+00, -1.04897738e-01, -5.38441002e-01,  5.12129009e-01,
       -2.99697310e-01, -3.39489400e-01,  8.42997849e-01,  4.27488238e-01,
        2.00435829e+00, -3.41050357e-01, -1.35862440e-01,  4.94593590e-01,
        4.60641980e-01,  2.26533309e-01,  6.49082363e-01, -9.27296460e-01,
       -8.98437619e-01, -7.47627094e-02, -5.17271161e-02,  4.24266160e-01,
        2.04907727e+00, -1.03697765e+00, -7.39458203e-02, -1.03839837e-01,
        9.12102610e-02, -7.82224596e-01,  1.22685000e-01,  5.25478065e-01,
        8.77941310e-01, -1.07035089e+00,  1.14516437e+00, -6.85251355e-02,
       -2.07095578e-01,  8.25668097e-01, -6.97912872e-01, -4.33360904e-01,
       -1.01111877e+00, -1.23771295e-01,  3.72816116e-01,  1.43643165e+00,
        2.59675086e-01,  2.40400825e-02,  1.44072548e-01, -2.92705536e-01,
       -4.56666350e-01, -1.03121471e+00, -3.42651419e-02,  1.11723387e+00,
       -8.05009365e-01, -1.06371427e+00,  9.39528048e-01, -1.10961080e+00,
       -5.70033967e-01,  2.82131106e-01,  9.81011569e-01,  7.42336929e-01,
        3.45889509e-01, -1.52945668e-01,  5.06053925e-01,  8.78180802e-01,
       -1.09631836e+00, -1.18013501e+00,  3.29545647e-01,  9.71300721e-01,
        8.07017565e-01, -9.65718985e-01, -1.35567355e+00, -4.26576465e-01,
        8.72841001e-01,  9.12704706e-01,  5.53129256e-01, -3.01382303e-01,
        2.44822547e-01,  4.60556895e-01,  5.09462655e-01,  2.33187869e-01,
       -8.34471807e-02, -8.73060465e-01, -8.56947452e-02, -1.18896127e+00,
        4.45140392e-01,  1.25609243e+00, -8.02383006e-01,  2.53110588e-01,
       -1.61043331e-01,  1.00251532e+00,  1.22520065e+00, -7.20697641e-01,
       -2.66761631e-01, -4.04146940e-01,  2.10683256e-01,  1.87888491e+00,
       -2.28521109e-01, -6.12844586e-01, -6.65905535e-01,  3.91878635e-01,
        3.66186917e-01,  5.24441481e-01, -5.60477674e-02, -8.25320244e-01,
       -4.08005536e-01,  8.48397851e-01, -1.78851438e+00,  1.05443537e+00,
       -4.94988918e-01,  8.59233737e-02,  8.05799663e-01, -8.11086655e-01,
       -1.53126836e+00,  1.26099706e+00,  2.32929498e-01,  7.63362586e-01,
        1.01791656e+00,  5.86199283e-04, -1.36577344e+00,  6.96269274e-01,
       -8.03744137e-01, -6.67104661e-01, -1.23582244e+00, -4.29341376e-01,
       -1.30704075e-01, -2.88134515e-01, -4.87712651e-01,  1.41323662e+00,
        5.98401427e-01,  1.54006138e-01,  4.15773809e-01, -5.96301138e-01,
       -1.04718339e+00,  7.55836964e-01,  3.30549896e-01, -3.29785407e-01],
      dtype=float32)

In [15]:
words = list(model.wv.index_to_key)

In [17]:
# words

In [20]:
import torch 
import torch.nn as nn

In [22]:
# Get a dictionary mapping of the vocab
word_map = {
    word:idx
    for idx,word in enumerate(model.wv.key_to_index, start=2)
}
# word_map

In [23]:
 (
    df
    .text
    .apply(lambda x: x.split(" "))
)[0]

['tivani',
 'vietnam',
 'furnitureco',
 'ltdno',
 'dongkhoistreet',
 'zone',
 'hoaphuward',
 'thudaumotc',
 'binhduongprovincetel',
 'fax',
 'stuffingdetail',
 'loadingchartloadingd',
 'ponumb',
 'stockton',
 'cafinaldestin',
 'tivanyportofdischargeetdd',
 'containers',
 'hcetad',
 'sep',
 'oct',
 'acontainernumb',
 'tcnu',
 'sealnumb',
 'itemcodeorderqtyloadedqtyremarkssa',
 'ag',
 'jvsertaocaugustinepulloutqueensizesofaandtrackarmupholsterygradesojava',
 'uso',
 'withpipingburlywood',
 'additionalinform',
 'detail',
 'replacementpart',
 'sampleitem',
 'sertaccaugustinepulloutqueensizesofaandtrackarmupholsterygrad',
 'java',
 'withpipingburlywood',
 'othersitem',
 'factoryitem',
 'otherfactoryitern',
 'fumigationfe',
 'cartonscarton',
 'remark',
 'loadedbi',
 'factorycomekordatkiteyanycheckedbi',
 'factorycheckedandconfirmedbycustomerrep',
 'lifestylesolutionsqc',
 'name',
 'tivanynam',
 'tivanynam',
 'idno',
 'idno',
 'idno',
 'date',
 'date',
 'date']

In [24]:
training_sentence_data = (
    df
    .text
    .apply(lambda x: list(map(lambda word: word_map[word] if word in word_map else 1, x.split(" "))))
)
print(training_sentence_data[0])

[2039, 146, 19343, 11675, 19302, 308, 15069, 18171, 1, 50, 38821, 1, 24471, 2890, 1, 1, 12538, 30239, 118, 331, 56894, 928, 11644, 1, 2043, 1, 6993, 1, 1, 176, 26700, 26625, 1, 4898, 1, 30247, 26612, 1, 37147, 1, 222, 30250, 1, 1, 1, 10, 37146, 37146, 24357, 24357, 24357, 5, 5, 5]

In [26]:
sentence_length = df.text.apply(lambda x: x.split(" ")).apply(len).max()
sentence_length

3502

In [27]:
training_sentence_data = (
    list(
        map(
            lambda x: pd.np.pad(x, (0, sentence_length-len(x))), 
            training_sentence_data
        )
    )
)
training_sentence_data[0]

C:\Users\JatinGogia\anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  after removing the cwd from sys.path.

array([ 2039,   146, 19343, ...,     0,     0,     0])

In [28]:
torch.LongTensor(training_sentence_data[0])

tensor([ 2039,   146, 19343,  ...,     0,     0,     0])

In [29]:
training_sentence_data = (
    list(
        map(
            lambda x: torch.LongTensor(x), 
            training_sentence_data
        )
    )
)
training_sentence_data[0]

tensor([ 2039,   146, 19343,  ...,     0,     0,     0])

In [30]:
model.wv.vectors.shape

(68614, 100)

In [31]:
word_vectors_for_training = pd.np.insert(
    model.wv.vectors,   
    0, 
    pd.np.random.uniform(model.wv.vectors.min(),model.wv.vectors.max(),100),
    axis=0
)

word_vectors_for_training = pd.np.insert(
    word_vectors_for_training,   
    0, 
    pd.np.zeros(100),
    axis=0
)
word_vectors_for_training = torch.FloatTensor(word_vectors_for_training)
word_vectors_for_training.shape

C:\Users\JatinGogia\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  """Entry point for launching an IPython kernel.
C:\Users\JatinGogia\anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  after removing the cwd from sys.path.
C:\Users\JatinGogia\anaconda3\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

C:\Users\JatinGogia\anaconda3\lib\site-packages\ipykernel_launcher.py:11: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  # This is added back by InteractiveShellApp.init_path()

torch.Size([68616, 100])

In [32]:
class FirstNeuralNetwork(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super().__init__()
        self.embedding_layer = nn.EmbeddingBag.from_pretrained(word_vectors_for_training, mode="mean")
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.layer2 = nn.Linear(hidden_size, num_classes)
    
    def forward(self, data_input):
        embedded_data_input = self.embedding_layer(data_input)
        output_layer1 = self.layer1(embedded_data_input)
        output_layer1 = self.relu(output_layer1)
        output_layer2 = self.layer2(output_layer1)
        # return the predictions but drop the axis
        return output_layer2.squeeze()

In [35]:
df=pd.read_excel(r'training_data_with_augmentation_nlp_done.xlsx')
df.head()

,SHIPMENT_ID,DOCUMENT_ID,REMOTE_LOCATION,DOCUMENT_TYPE,TEXT_CONTENT,text
0,KX-D7I0-109,Jzg2XHurxjUOvTrmzuzf,1950156944-2124289811-44413_44436shippingdocs-...,0,PO#: 44413 / 44436\nORDER\nPALLET\n1-8\n9-16\n...,order pallet load detail sku cpe cpe empti box...
1,KX-J4J4-2,7Y986NV4O6fKCUtGUqZM,1954265047-326617438-TerminalHandlingCharges-H...,0,PayCargo\n• Created by KlearNow Corp from Klea...,paycargo creat klearnow corp klearnow corp sep...
2,KX-J4J4-2,c0eQC0f4FEvK5p3Y9GBh,1954265047-326617438-TerminalHandlingCharges-H...,0,Payment Details\nPayCargo\nMethod\nOvernight\n...,payment detail paycargo method overnight trans...
3,KX-E5G4-5767,0q2UC7nnnqw21hPzQcOY,1964909868-1563419258-AR_221203591-1.png,0,"GREAT LUCK INC.\n1861 WESTERN WAY TORRANCE, CA...",great luck inc western way torranc tel email l...
4,KX-E5G4-5767,ytk1qRbji8Ra13tl98qs,1964909868-480001211-AR_22118434-1.png,0,"GREAT LUCK INC.\n1861 WESTERN WAY TORRANCE, CA...",great luck inc western way torranc tel email l...

In [40]:
df['data_type']=df['DOCUMENT_ID'].apply(lambda x:'augmented' if 'augmented' in x else 'original')

In [43]:
df.to_excel(r'training_data_with_augmentation_nlp_done_stemmed_final.xlsx',index=False)